#!/usr/bin/perl
# gen-fonts-css.pl - materialise a theme's self-hosted fonts at packaging time.
#
#   gen-fonts-css.pl <fonts.list> <fonts-store-dir> <dest-assets-dir>
#
# Reads a fonts.list (lines of "Family Name:400,500i,700" - weights
# comma-separated, "i" suffix = italic, "#" comments allowed), resolves each
# requested face via <fonts-store-dir>/fonts.json, then writes into the
# destination assets dir:
#
#   fonts.css          @font-face per requested face, font-display: swap,
#                      src: url('fonts/<file>') format('woff2')
#   fonts/<file>.woff2 the deduplicated font files those faces resolve to
#   fonts/OFL-<slug>.txt  each family's licence (OFL requires it to travel
#                      with the font files)
#
# Dies (non-zero exit) on an unknown family or an unlisted weight, so a
# typo in fonts.list fails the packaging build instead of shipping a
# broken theme. No network access, ever.
use strict;
use warnings;
use JSON::PP   ();
use File::Copy ();

@ARGV == 3 or die "usage: gen-fonts-css.pl <fonts.list> <fonts-store-dir> <dest-assets-dir>\n";
my ( $list_path, $store_dir, $dest_dir ) = @ARGV;

-f $list_path or die "no such fonts.list: $list_path\n";
-d $store_dir or die "no such fonts store: $store_dir\n";
-d $dest_dir  or die "no such destination dir: $dest_dir\n";

my $map = do {
    open my $fh, '<:raw', "$store_dir/fonts.json"
        or die "read $store_dir/fonts.json: $!\n";
    my $raw = do { local $/; <$fh> };
    JSON::PP->new->decode($raw);
};

sub slugify {
    my ($name) = @_;
    ( my $slug = lc $name ) =~ s/\s+/-/g;
    return $slug;
}

my ( @css_blocks, %copy_files, %copy_licences );

open my $lf, '<', $list_path or die "read $list_path: $!\n";
while ( my $line = <$lf> ) {
    chomp $line;
    $line =~ s/#.*$//;
    $line =~ s/^\s+|\s+$//g;
    next unless length $line;
    my ( $family, $weights ) = $line =~ /^([^:]+?)\s*:\s*(\S+)$/
        or die "$list_path: unparseable line: $line\n";
    my $slug  = slugify($family);
    my $entry = $map->{$slug}
        or die "$list_path: unknown family '$family' (no fonts/$slug in store)\n";

    for my $spec ( split /,/, $weights ) {
        my ( $weight, $italic ) = $spec =~ /^(\d+)(i?)$/
            or die "$list_path: bad weight spec '$spec' for $family\n";
        my $style = $italic ? 'italic' : 'normal';
        my ($face) = grep { $_->{style} eq $style && $_->{weight} == $weight }
            @{ $entry->{faces} };
        $face
            or die "$list_path: $family $weight$italic not in store "
            . "(add the face to fonts/ + fonts.json first)\n";
        my $src = "$store_dir/$slug/$face->{file}";
        -f $src or die "store file missing: $src\n";
        $copy_files{ $face->{file} } = $src;
        $copy_licences{$slug} = "$store_dir/$slug/OFL.txt";
        push @css_blocks, <<"CSS";
\@font-face {
  font-family: '$entry->{family}';
  font-style: $style;
  font-weight: $weight;
  font-display: swap;
  src: url('fonts/$face->{file}') format('woff2');
}
CSS
    }
}
close $lf;

@css_blocks or die "$list_path: no faces requested\n";

mkdir "$dest_dir/fonts" unless -d "$dest_dir/fonts";
for my $file ( sort keys %copy_files ) {
    File::Copy::copy( $copy_files{$file}, "$dest_dir/fonts/$file" )
        or die "copy $file: $!\n";
}
for my $slug ( sort keys %copy_licences ) {
    -f $copy_licences{$slug} or die "missing licence: $copy_licences{$slug}\n";
    File::Copy::copy( $copy_licences{$slug}, "$dest_dir/fonts/OFL-$slug.txt" )
        or die "copy OFL-$slug.txt: $!\n";
}

my $header = "/* Self-hosted fonts - generated by tools/gen-fonts-css.pl.\n"
    . " * Latin subsets, OFL 1.1 (licences alongside the files in fonts/).\n"
    . " * Standing policy: no CDN - do not replace with external links. */\n";
open my $out, '>', "$dest_dir/fonts.css" or die "write fonts.css: $!\n";
print {$out} $header, join( '', @css_blocks );
close $out;

printf "  fonts: %d faces, %d files -> %s\n",
    scalar @css_blocks, scalar keys %copy_files, "$dest_dir/fonts.css";
